### ISSUE TITLE
感谢分享，请教几个问题

### ISSUE THREAD

**Issue by y655r** [weiyinfu/JinYong#1]
您好，感谢分享，之前网上下载的版本文本错误太多。请教您“三联23版”的元数据来源？是官方购买的正版吗？“新修版”文本错误多吗？

**Comment by weiyinfu** [comment]
“三联23版”是从一个pdf文件里面里面提取出来的，存在换行的问题，一行字数够了就换行了，所以多了很多换行符。
金庸全集三联版：很久之前整理的，错误非常多。
金庸三联版：从另一个github仓库搞来的，据我观察没什么错误。
